controller_list:
  - name: fake_roka_controller
    joints:
      - joint 1
      - Joint 2
      - Joint 3
      - Joint 4
      - Joint 5
      - Joint 6
  - name: fake_tool_controller
    joints:
      []
initial:  # Define initial robot poses.
#  - group: roka
#    pose: home
